using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraController : MonoBehaviour
{
    // Objeto que representa al player
    public GameObject player;
    // Distancia entre la c치mara y el player
    private Vector3 offset;

    // Start is called before the first frame update
    void Start()
    {
        // Calculamos el offset entre la c치mara y el jugador para mantener la distancia constante
        offset = transform.position - player.transform.position; 
    }

    // Update is called once per frame
    void LateUpdate()
    {
        // La c치mara sigue al jugador, pero mantiene su offset, sin movimiento con el rat칩n
        transform.position = player.transform.position + offset;
    }
}

